# Site settings
title: Laurynn Coleman
email: colemanlaurynn@gmail.com
url: https://LaurynnColeman.github.io
description: "Data Analyst passionate about storytelling with data, visualizations, and machine learning. Explore some of my projects in Power BI, R, and Python!"
keywords: "Data Analytics, Data Science, Machine Learning, Data Visualization, Power BI, Tableau, Python, R, SQL"
skills: "Data Analyst - Machine Learning - Data Visualization - NLP - Power BI"
meta_author: Coleman Laurynn

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff66b2  # Soft pink for highlights (buttons, links)
  primary-rgb: "255,102,178"  
  secondary: 8a2be2  # Lavender
  secondary-dark: 6c1bb5  # Darker shade of lavender for contrast

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/laurynn-coleman-a4a33a183/
  - title: github
    url: http://github.com/jekyll

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
